/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asistenciaspartans;

import com.digitalpersona.onetouch.DPFPGlobal;
import ds.desktop.notify.DesktopNotify;
import java.io.IOException;
import java.text.Normalizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-Programador4
 */
public class Enrrolar extends javax.swing.JPanel {

    Principal principal = null;

    public Enrrolar(Principal principalAux) {
        principal = principalAux;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTDocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jBEnrrolar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jFTFechaNacimiento = new javax.swing.JFormattedTextField();
        jTIdUsuario = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(237, 203, 10));
        jLabel1.setForeground(new java.awt.Color(237, 203, 10));
        jLabel1.setText("Documento:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTDocumento.setEditable(false);
        add(jTDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 274, -1));

        jLabel2.setBackground(new java.awt.Color(237, 203, 10));
        jLabel2.setForeground(new java.awt.Color(237, 203, 10));
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTNombre.setEditable(false);
        add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 274, -1));

        jLabel3.setBackground(new java.awt.Color(237, 203, 10));
        jLabel3.setForeground(new java.awt.Color(237, 203, 10));
        jLabel3.setText("Fecha de nacimiento: yyyy-MM-dd");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jBBuscar.setForeground(new java.awt.Color(237, 203, 10));
        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_32.png"))); // NOI18N
        jBBuscar.setText("BUSCAR");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jBEnrrolar.setForeground(new java.awt.Color(237, 203, 10));
        jBEnrrolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enrrolar_32.png"))); // NOI18N
        jBEnrrolar.setText("ENRROLAR");
        jBEnrrolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnrrolarActionPerformed(evt);
            }
        });
        add(jBEnrrolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jBGuardar.setForeground(new java.awt.Color(237, 203, 10));
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar_32.png"))); // NOI18N
        jBGuardar.setText("GUARDAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        jFTFechaNacimiento.setEditable(false);
        jFTFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        add(jFTFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 270, -1));

        jTIdUsuario.setEditable(false);
        jTIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdUsuarioActionPerformed(evt);
            }
        });
        add(jTIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        String documento = JOptionPane.showInputDialog("Digite el documento de identidad:");
        try {
            Biometrico biometricoOBJ = new Biometrico();
            RespuestaServidor respuestaOBJ = biometricoOBJ.buscarUsuario(documento);
            if (respuestaOBJ.getResponseCode() == 200) {
                if (respuestaOBJ.getUsuarioExiste() == 0) {
                    JOptionPane.showMessageDialog(this, "Usuario no existe", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    String cadenaNombre = Normalizer.normalize(respuestaOBJ.getNombreUsuario(), Normalizer.Form.NFD);
                    String nombreSinAcentos = cadenaNombre.replaceAll("[^\\p{ASCII}]", "");
                    jTDocumento.setText(respuestaOBJ.getDocumentoUsuario());
                    jTNombre.setText(nombreSinAcentos);
                    jFTFechaNacimiento.setText(respuestaOBJ.getFechaNacimiento());
                    jTIdUsuario.setText(respuestaOBJ.getIdClienteEmpleado());
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Enrrolar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEnrrolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnrrolarActionPerformed
        String documento = jTDocumento.getText();
        String nombre = jTNombre.getText();
        String fechaNac = jFTFechaNacimiento.getText();

        if (documento.length() == 0 || nombre.length() == 0 || fechaNac.length() == 0) {
            JOptionPane.showMessageDialog(this, "Los campos no deben estar vacios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            principal.onEnroll();
        }
    }//GEN-LAST:event_jBEnrrolarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        String documento = jTDocumento.getText();
        String idClienteEmpleado = jTIdUsuario.getText();
        String nombre = jTNombre.getText();
        String fechaNacimiento = jFTFechaNacimiento.getText();

        if (documento.length() == 0 || nombre.length() == 0 || fechaNacimiento.length() == 0) {
            JOptionPane.showMessageDialog(this, "Los campos no deben estar vacios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (principal != null) {
            if (principal.template == null) {
                JOptionPane.showMessageDialog(this, "Debes enrrolar una huella", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    int pregunta = JOptionPane.showConfirmDialog(this, "¿Desea guardar la informacion?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if (pregunta == 0) {
                        Biometrico biometricoOBJ = new Biometrico();
                        RespuestaServidor respuestaOBJ = biometricoOBJ.onSave(documento, idClienteEmpleado, nombre, fechaNacimiento, principal.getTemplate(), DPFPGlobal.getSampleConversionFactory().createImage(principal.getSampleAux()));
                        if (respuestaOBJ.getUsuarioExiste() == 1) {
                            JOptionPane.showMessageDialog(this, "Error, el usuario " + nombre + "\nya se encuentra enrrolado anteriormente.", "Error", JOptionPane.ERROR_MESSAGE);
                            DesktopNotify.showDesktopMessage("Mensaje de Error", "El usuario " + nombre + " ya se encuentra enrrolado anteriormente.", DesktopNotify.ERROR);
                            principal.template = null;
                            jTDocumento.setText("");
                            jTIdUsuario.setText("");
                            jTNombre.setText("");
                            jFTFechaNacimiento.setText("");
                            jTDocumento.requestFocus();
                        } else {
                            JOptionPane.showMessageDialog(this, "Correcto, el usuario " + nombre + "\nya se encuentra enrrolado.", "Enrrolamiento con exito", JOptionPane.INFORMATION_MESSAGE);
                            DesktopNotify.showDesktopMessage("Enrrolamiento con exito", "Usuario " + nombre + " ya se encuentra enrrolado.", DesktopNotify.SUCCESS);
                            principal.template = null;
                            jTDocumento.setText("");
                            jTIdUsuario.setText("");
                            jTNombre.setText("");
                            jFTFechaNacimiento.setText("");
                            jTDocumento.requestFocus();
                        }
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Enrrolar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes enrrolar una huella", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIdUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEnrrolar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JFormattedTextField jFTFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTDocumento;
    private javax.swing.JTextField jTIdUsuario;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
